service:
  name: projectIssueTracker
frameworkVersion: '2'
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  documentation:
    api:
      info:
        version: v1.0.0
        title: Udacity Todo API
        description: Serverless application for todos
    models:
      - name: CreateProjectRequest
        contentType: application/json
        schema: ${file(models/create-project-request.json)}
      - name: CreateIssueRequest
        contentType: application/json
        schema: ${file(models/create-issue-request.json)}
      - name: UpdateIssueRequest
        contentType: application/json
        schema: ${file(models/update-issue-request.json)}
      
plugins: 
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation
provider:
  name: aws
  runtime: nodejs12.x
  apitGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    JWKS_URL: https://dev-xmbz3y4p.us.auth0.com/.well-known/jwks.json
    PROJECT_ISSUES_TABLE: Project_Issues-${self:provider.stage}
    
functions:
  Auth:
    handler: src/lambda/auth/authorizer.handler
  GetProjects:
    handler: src/lambda/http/getProjects.handler
    events:
      - http:
          method: get
          path: projects
          cors: true
          authorizer: Auth
    iamRoleStatements:
      - Effect: Allow
        Action:
            - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PROJECT_ISSUES_TABLE}
  CreateProjects:
    handler: src/lambda/http/createProject.handler
    events:
      - http:
          method: post
          path: projects
          cors: true
          authorizer: Auth
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: Create a new project
            description: Create a new project
            requestModels:
              'application/json': CreateProjectRequest
    iamRoleStatements:
      - Effect: Allow
        Action:
            - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PROJECT_ISSUES_TABLE}
  GetProject:
    handler: src/lambda/http/getProject.handler
    events:
      - http:
          method: get
          path: projects/{projectId}
          cors: true
          authorizer: Auth
    iamRoleStatements:
      - Effect: Allow
        Action:
            - dynamodb:GetItem
            - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PROJECT_ISSUES_TABLE}
  CreateIssue:
    handler: src/lambda/http/createIssue.handler
    events:
      - http:
          method: post
          path: issues
          cors: true
          authorizer: Auth
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: Create a new Issue
            description: Create a new Issue
            requestModels:
              'application/json': CreateIssueRequest
    iamRoleStatements:
      - Effect: Allow
        Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PROJECT_ISSUES_TABLE}
  UpdateIssue:
    handler: src/lambda/http/updateIssue.handler
    events:
      - http:
          method: patch
          path: issues/{issueId}
          cors: true
          authorizer: Auth
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: Update an Issue
            description: Update an Issue
            requestModels:
              'application/json': UpdateIssueRequest
    iamRoleStatements:
      - Effect: Allow
        Action:
            - dynamodb:UpdateItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PROJECT_ISSUES_TABLE}
      - Effect: 'Allow'
        Action:
          - 'xray:PutTraceSegments'
          - 'xray:PutTelemetryRecords'
        Resource:
          - '*'
        
resources:
  Resources:
    RequestBodyValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: 'request-body-validator'
        RestApiId: 
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false
    ProjectIssuesTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.PROJECT_ISSUES_TABLE}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

        